POST http://localhost:8080/api/public/centers/reservation
Content-Type: application/json

{
    "firstName" : "poivron",
    "lastName": "pesto",
    "mail": "basilic@coucou.com",
    "dateRDV" : "2023-10-19",
    "vaccinationCenter" : {
        "id" : 1
        },
    "valid" : 0

}

#  {
#         "firstName": "hohoho",
#         "lastName": "salut",
#         "mail": "couc@coucou.ciom",
#         "dateRDV": "2023-10-15",
#         "vaccinationCenter": {
#           "id": 2
#         }
#  }
////////marche pas