//GET http://localhost:8080/api/public/utilisateur?login=chocolat

//GET http://localhost:8080/api/public/login?login=cacao
//GET http://localhost:8080/api/utilisateur

GET http://localhost:8080/api/public/utilisateur/