# POST http://localhost:8080/api/private/utilisateurs
# Content-Type: application/json

# {
#     "login" : "crumble",
#     "password": "tartare", 
#     "nom": "tartetatin",  
#     "prenom" : "croissant",
#     "email": "hahaha@hey.comm",
#     "roles": "med"

# }
