spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: Stella36
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
#le mettre en commentaires si il y a des données dans la bdd

  # management:
  #   endpoints:
  #     jmx:
  #       exposure:
  #         include: info,health,beans,metrics,endpoints,mappings
  #     web:
  #       exposure:
  #         include: health,info,prometheus,metrics

    

